@startuml
class twisk.simulation.Client {
- Etape etape
- int numeroClient
- int rang
+ void allerA(Etape,int)
+ Etape getEtape()
+ int getNumeroClient()
+ int getRang()
+ String toString()
}
class twisk.simulation.Simulation {
- int nbClients
- GestionnaireClients gestCli
+ void simuler(Monde)
+ int[] start_simulation(int,int,int,int[])
+ int[] ou_sont_les_clients(int,int)
+ void nettoyage()
+ void setNbClients(int)
}
class twisk.simulation.GestionnaireClients {
- Client[] clients
+ void setClients(int)
+ void allerA(int,Etape,int)
+ void reset()
+ Iterator<Client> iterator()
+ Client getClientI(int)
}


twisk.simulation.Iterable <|.. twisk.simulation.GestionnaireClients
@enduml