@startuml
interface twisk.designPattern.Observateur {
~ void reagir()
}
class twisk.designPattern.SujetObserve {
+ void ajouterObservateur(Observateur)
+ void notifierObservateurs()
}
twisk.designPattern.SujetObserve "1"--"*" twisk.designPattern.Observateur
@enduml